# This file created by conda-build 3.21.9
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed Jun  1 14:27:44 2022
# ------------------------------------------------

package:
  name: micromamba
  version: 0.24.0
source:
  - patches:
      - libmamba.patch
    sha256: 86bdf480069dcc0b863da74ca4248942f5aeaa75004ab52d4829ec8b202d9086
    url: https://github.com/mamba-org/mamba/archive/refs/tags/micromamba-0.24.0.tar.gz
build:
  ignore_run_exports_from:
    - gcc_linux-64 10.*
    - gxx_linux-64 10.*
    - libarchive
    - libcurl
    - openssl
    - reproc-cpp
    - spdlog
  number: '0'
  string: '0'
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.36.1 h193b22a_2
    - binutils_linux-64 2.36 hf3e587d_10
    - bzip2 1.0.8 h7f98852_4
    - c-ares 1.18.1 h7f98852_0
    - ca-certificates 2022.5.18.1 ha878542_0
    - cmake 3.23.2 h5432695_0
    - expat 2.4.8 h27087fc_0
    - gcc_impl_linux-64 10.3.0 hf2f2afa_16
    - gcc_linux-64 10.3.0 hc39de41_10
    - gxx_impl_linux-64 10.3.0 hf2f2afa_16
    - gxx_linux-64 10.3.0 h2593f52_10
    - kernel-headers_linux-64 2.6.32 he073ed8_15
    - keyutils 1.6.1 h166bdaf_0
    - krb5 1.19.3 h08a2579_0
    - ld_impl_linux-64 2.36.1 hea4e1c9_2
    - libcurl 7.83.1 h2283fc2_0
    - libedit 3.1.20191231 he28a2e2_2
    - libev 4.33 h516909a_1
    - libgcc-devel_linux-64 10.3.0 he6cfe16_16
    - libgcc-ng 12.1.0 h8d9b700_16
    - libgomp 12.1.0 h8d9b700_16
    - libnghttp2 1.47.0 he49606f_0
    - libsanitizer 10.3.0 h26c7422_16
    - libssh2 1.10.0 ha35d2d1_2
    - libstdcxx-devel_linux-64 10.3.0 he6cfe16_16
    - libstdcxx-ng 12.1.0 ha89aaad_16
    - libuv 1.43.0 h7f98852_0
    - libzlib 1.2.12 h166bdaf_0
    - lz4-c 1.9.3 h9c3ff4c_1
    - make 4.3 hd18ef5c_1
    - ncurses 6.3 h27087fc_1
    - openssl 3.0.3 h166bdaf_0
    - rhash 1.4.1 h7f98852_0
    - sysroot_linux-64 2.12 he073ed8_15
    - xz 5.2.5 h516909a_1
    - zlib 1.2.12 h166bdaf_0
    - zstd 1.5.2 h8a70e8d_1
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h7f98852_4
    - c-ares 1.18.1 h7f98852_0
    - c-ares-static 1.18.1 h7f98852_0
    - ca-certificates 2022.5.18.1 ha878542_0
    - cli11 2.2.0 h27087fc_0
    - cpp-expected 1.0.0 h924138e_0
    - cpp-filesystem 1.5.12 h924138e_0
    - icu 70.1 h27087fc_0
    - keyutils 1.6.1 h166bdaf_0
    - krb5 1.19.3 h3790be6_0
    - krb5-static 1.19.3 h3790be6_0
    - libarchive 3.3.3 hddc7a2b_1008
    - libcurl 7.83.1 h7bff187_0
    - libcurl-static 7.83.1 h7bff187_0
    - libedit 3.1.20191231 he28a2e2_2
    - libev 4.33 h516909a_1
    - libev-static 4.33 h516909a_1
    - libgcc-ng 12.1.0 h8d9b700_16
    - libgomp 12.1.0 h8d9b700_16
    - libiconv 1.16 h516909a_0
    - libnghttp2 1.47.0 h727a467_0
    - libnghttp2-static 1.47.0 h3790be6_0
    - libopenssl-static 1.1.1o h166bdaf_0
    - libsolv 0.7.22 h6239696_0
    - libsolv-static 0.7.22 h6239696_0
    - libssh2 1.10.0 ha56f1ee_2
    - libssh2-static 1.10.0 ha56f1ee_2
    - libstdcxx-ng 12.1.0 ha89aaad_16
    - libxml2 2.9.14 h22db469_0
    - libzlib 1.2.12 h166bdaf_0
    - lz4-c 1.9.2 he1b5a44_3
    - lz4-c-static 1.9.3 ha770c72_1
    - lzo 2.10 h516909a_1000
    - ncurses 6.3 h27087fc_1
    - nlohmann_json 3.10.5 h9c3ff4c_0
    - openssl 1.1.1o h166bdaf_0
    - reproc 14.2.3 h7f98852_0
    - reproc-cpp 14.2.3 h9c3ff4c_0
    - reproc-cpp-static 14.2.3 h9c3ff4c_0
    - reproc-static 14.2.3 h7f98852_0
    - spdlog 1.10.0 h924138e_0
    - termcolor-cpp 2.0.0 h4bd325d_0
    - xz 5.2.5 h516909a_1
    - xz-static 5.2.5 h516909a_1
    - yaml-cpp 0.7.0 h27087fc_1
    - yaml-cpp-static 0.7.0 h27087fc_1
    - zlib 1.2.12 h166bdaf_0
    - zstd 1.4.8 hdf46e1d_0
    - zstd-static 1.4.8 h9c3ff4c_0
  run: []
test:
  commands:
    - test -f $PREFIX/bin/micromamba
    - micromamba --help
    - export TMPDIR="${TMPDIR:-/tmp}"
    - if [ ! -d "${TMPDIR}" ]; then mkdir -p "${TMPDIR}"; fi
    - stat $TMPDIR
    - export MAMBA_ROOT_PREFIX=$TMPDIR/mamba
    - micromamba create -p $TMPDIR/testenv --override-channels -c conda-forge --yes
      python=3.9
    - $TMPDIR/testenv/bin/python --version
    - $TMPDIR/testenv/bin/python -c 'import ssl'
about:
  dev_url: https://github.com/mamba-org/mamba
  home: https://github.com/mamba-org/mamba
  license: BSD-3-Clause AND MIT AND OpenSSL
  license_family: BSD
  license_file:
    - CLI11_LICENSE.txt
    - CPP_FILESYSTEM_LICENSE.txt
    - CURL_LICENSE.txt
    - C_ARES_LICENSE.txt
    - KRB5_LICENSE.txt
    - LIBARCHIVE_LICENSE.txt
    - LIBEV_LICENSE.txt
    - LIBLZ4_LICENSE.txt
    - LIBNGHTTP2_LICENSE.txt
    - LIBOPENSSL_3_LICENSE.txt
    - LIBOPENSSL_LICENSE.txt
    - LIBSOLV_LICENSE.txt
    - LICENSE
    - NLOHMANN_JSON_LICENSE.txt
    - REPROC_LICENSE.txt
    - SPDLOG_LICENSE.txt
    - TERMCOLOR_CPP_LICENSE.txt
    - ZSTD_LICENSE.txt
  summary: Micromamba is a tiny version of mamba, the fast conda package installer.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - JohanMabille
    - SylvainCorlay
    - adriendelsalle
    - mariusvniekerk
    - wolfv
